export const API_URL = '/api' ;
export const API_DIRECCIONES = API_URL + '/direcciones'
export const API_CARRERAS = API_URL + '/carreras'
export const API_ASIGNATURAS = API_URL + '/asignaturas'
export const API_LABORATORIOS = API_URL + '/laboratorios'
export const API_CUATRIMESTRES = API_URL + '/cuatrimestres'
export const METODO_LISTAR = 'GET';
export const METODO_DETALLE = 'GET';
export const METODO_CREAR = 'POST';
export const METODO_EDITAR = 'PUT';
export const METODO_BORRAR = 'DELETE';
export const API_TOKEN = '1|heZtmZm71L6DSaDU8Fw86tswt6xJuPaRybmuTGfo00e03aa2';
export const CREAR = 'crear';
export const EDITAR = 'editar';