export const API_URL = '/api' ;
export const API_DIRECCIONES = API_URL + '/direcciones'
export const METODO_LISTAR = 'GET';
export const METODO_DETALLE = 'GET';
export const METODO_CREAR = 'POST';
export const METODO_EDITAR = 'PUT';
export const METODO_BORRAR = 'DELETE';
export const API_TOKEN = '2|p1OQ9pwBeWWUiMILIM6XEHcMDZoFychzR7NmQqHCb215bc5b';
export const CREAR = 'crear';
export const EDITAR = 'editar';