export const API_URL = '/api' ;
export const API_DIRECCIONES = API_URL + '/direcciones'
export const API_CARRERAS = API_URL + '/carreras'
export const API_ASIGNATURAS = API_URL + '/asignaturas'
export const API_LABORATORIOS = API_URL + '/laboratorios'
export const API_CUATRIMESTRES = API_URL + '/cuatrimestres'
export const API_UNIDADES_MEDIDAS = API_URL + '/unidades_medidas'
export const API_MATERIALES = API_URL + '/materiales'
export const API_DIAS_FERIADOS = API_URL + '/dias_feriados'
export const API_GRUPOS_LABORATORIOS = API_URL + '/grupos_laboratorios'
export const API_FORMATOS_LABORATORIOS = API_URL + '/formatos_laboratorios'
export const API_DETALLES_FORMATOS_LABORATORIOS = API_URL + '/detalle_formato_laboratorio'
export const METODO_LISTAR = 'GET';
export const METODO_DETALLE = 'GET';
export const METODO_CREAR = 'POST';
export const METODO_EDITAR = 'PUT';
export const METODO_BORRAR = 'DELETE';
export const API_TOKEN = '1|fqPKZLSmN6QEXrrGUUpQgCrLf27hco7pU0nl2Q1e3246fef8';
export const CREAR = 'crear';
export const EDITAR = 'editar';